use rand::Rng;

const GREETINGS: &'static [&'static str] = &[
    "Die Zwölfe mit Euch",
    "Praios zum Gruße!",
    "Rondra zum Gruße!",
    "Efferd zum Gruße!",
    "Travia zum Gruße!",
    "Boron zum Gruße!",
    "Hesinde zum Gruße!",
    "Firun zum Gruße!",
    "Tsa zum Gruße!",
    "Phex zum Gruße!",
    "Peraine zum Gruße!",
    "Ingerimm zum Gruße!",
    "Rahja zum Gruße!",
    "Möge Peraine dich segnen (sonst kann ich dabei auch behilflich sein)",
    "Gebelaus mit dir",
    "Warum sind Zwergenwitze so kurz? Damit auch Elfen die verstehen.",
    "Was ist dümmer als ein Elf? Zwei Elfen.",
    "Wie viele Elfen braucht man, um eine Kuh zu töten? Fünf! Vier heben die Kuh hoch, und der fünfte frisst ihr das Gras weg.",
    "Wie treibt man einen Zwerg in den Wahnsinn? Man setzt ihn in einen runden Raum und sagt ihm, in der Ecke ist ein Schatz vergraben.",
    "Was ist ein Elf, der einen Zwerg beim Holzhacken gestört hat? Ein Halb-Elf",
    "Ehrenwerter Herr Medicus, können sie mir helfen?\nHmm, ich verschreibe ihnen erstmal ein paar Moorbäder.\nUnd die helfen?\nNein, aber sie gewöhnen sich schon mal an die feuchte Erde",
    "Möchtest du meinen Taschendrachen sehen?",
    "Excuse me, Milady, would you have a place where I may sheath my longsword?",
    "How'd you like to ride my stallion? He's well trained for battle!",
    "I am beset by this dragon in my loins, and only you can quench its fire!",
    "I hath done combat with many a beast, but I must confess that was the tightest situation I have ever been in.",
    "I lost my leg in battle. Guess what I'm walking on!",
    "Milady, it's not the size of the wand that matters, but the magic within.",
    "They say a knight is always as hard as his armor.",
    "Yes, I am indeed a wizard. Watch me make your clothes disappear!",
    "Is that ghoul poison in your pocket or are you just dying to see me?",
    "Come up and see my scrolls.",
    "Wizard: You know, my hat isn`t the only thing that`s pointed.",
    "Dost thou practice safe hex?",
    "Wanna polish my pike?",
    "Es scheint ich habe meinen Lustknabe verloren, kann ich dich ausleihen?",
    "Been there, slain that.",
    "I'd like to storm your castle!",
    "I'd buy you for 1 small horse, a falcon and a rabbit with one ear.",
    "Hey girl, I feel like you and me got some alchemy...",
    "Hey girl, are you a medusa? 'Cuz you're making me hard.",
    "I may not be a necromancer but I know how to make things rise.",
    "I’m going to need some fire resistance, because you’re hot.",
    "Bist du geweiht? Du bist so göttlich schön!",
    "Hast du Ignifaxius in mir gezaubert? Denn ich brenne für dich!",
    "I put the romance in necromancy.",
    "Ich möchte die Wege der Vereinigung mit dir testen",
    "Meine Sonderfertigkeit ist ‚Perfekt für dich‘",
    "In dieser Nacht werden wir sicher nicht viel regenerieren…",
    "Bist du ein Zaubertrick? Du scheinst ein echter Glücksgriff zu sein.",
    "Mich kann man übrigens im Bestiarium finden",
    "Hast du mir Quasselwurz gegeben? Ich kann nämlich nicht aufhören, über dich zu reden.",
    "Bist du ein Mindergeist? Du spukst immer in meinem Kopf herum.",
    "Hast du das Rahjalieb dabei?",
    "Bist du ein Golem? Du wirkst wie von Meisterhand erschaffen!",
    "Ich bin zwar ein Halbelf, aber ganz deins.",
    "Bist du ein Taschendieb? Du hast mein Herz gestohlen.",
    "Du hast eindeutig den Vorteil Gutaussehend, oder?",
    "Ja, ich habe die Sonderfertigkeit „Hose herunterziehen...",
    "Wie konntest du in der Nacht regenerieren? Du bist mir die ganze Zeit durch den Kopf gegangen",
    "Are you a Tiefling? Because you make me horny.",
    "Dein Vater muss ein Phex-Geweihter sein. Er hat die Sterne vom Himmel gestohlen und sie dir in die Augen gelegt.",
    "Rahja segne di- oh, das muss wohl schon geschehen sein.",
    "An welcher Akademie hast du studiert? Du bist so gut darin, mich zu verzaubern...",
    "Wie schaffst du es, dass es immer zur Praiosstunde wird, wenn du eintrittst?",
    "Du bist wie eine Einbeere. Du tust mir gut und ich will immer mehr von dir.",
    "Habe ich etwa heute Tsatag und du bist mein Geschenk?",
    "Seid ihr Magierin? Mein Zauberstab hört nicht auf zu wachsen...",
    "Ich bin mit einem Hexenfluch belegt, der nur gebrochen werden kann, wenn ich die Nacht mit der schönsten Frau der Stadt verbringe.",
    "Verphext und zugenäht...",
    "Als Hesinde Hirn verteilte, warst du krank",
    "Möge Tsa verhindern, dass du je Kinder bekommst.",
    "Dir hat Praios aber auch zulang auf den Kopf gestrahlt, oder?",
    "Du bist heut' wieder charmant wie ein Firunsjünger.",
    "Bei Praios leuchtendem Hinterteil!",
    "Dich könnte nicht mal Rahja lieben!",
    "Als Tsa dich schuf, war sie besoffen!",
    "Möge Efferd dir in beide Ohren pinkeln!",
    "Du siehst aus wie ein Shruuf!",
    "Vor deinem Mundgeruch läuft sogar der Namenslose weg!",
    "Ich würde ja die Wache rufen, aber ich fürchte, sie würde sich ob deiner Unfähigkeit zu Tode lachen. Mach, dass du verschwindest!",
    "I've recieved more witty banter from ghouls!",
    "No loot is worth having to look at you!",
    "Oh look, both your weapons are tiny!",
    "Would you like me to remove that curse? Oh, my mistake, you were just born that way!",
];

pub fn random_greeting() -> &'static str {
    let mut rng = rand::thread_rng();
    let line = rng.gen_range(0..GREETINGS.len());
    GREETINGS[line]
}
