name: CodeStyle

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      -
       name: Checkout
       uses: actions/checkout@v2
      -
       uses: actions-rs/toolchain@v1
       with:
          toolchain: stable
          components: rustfmt
          override: true
      - 
       name: Format
       run: "cargo fmt -- --check"
#      -
#       name: Lint
#       run: "cargo clippy -- -Dwarnings"
#      -
#       name: Test
#       run: "cargo test"