name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  # Run tests for any PRs.
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      -
       name: Checkout
       uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: dsacli/discord:master
          cache-from: type=registry,ref=dsacli/discord:buildcache
          cache-to: type=registry,ref=dsacli/discord:buildcache,mode=max
  deploy_webhook:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Webhook
      if: "${{ github.event_name == 'push' }}"
      uses: fjogeleit/http-request-action@master
      with:
        url: "${{ secrets.WEBHOOK_URL }}"
        method: 'POST'
        data: '{"secret":"${{ secrets.WEBHOOK_SECRET }}"}'